Repository weldr/lorax, pull requests merged in 2018-12, with the labels that each got.

#534 lorax-composer: Check the queue and results at startup
  src/pylorax/api/queue.py
  tests/pylorax/test_queue.py
Labels: f28-branch, f29-branch, master, rhel7-extras, rhel8-branch

#542 Add openstack to the image type list in the docs
  docs/composer-cli.rst
Labels: master, rhel8-branch

#552 Fix the compose_args for the backported images
  src/pylorax/api/compose.py
Labels: rhel7-extras
