Repository weldr/lorax, pull requests merged in 2018-08, with the labels that each got.

#417 Add a test for the pylorax.api.timestamp functions
  tests/pylorax/test_timestamp.py
Labels: rhel7-extras

#418 Add job_* timestamp support to compose status
  src/composer/cli/compose.py
Labels: f28-branch, master, rhel7-extras, rhel8-branch

#419 Add + to the allowed API string character set
  src/pylorax/api/regexes.py
Labels: f28-branch, master, rhel7-extras, rhel8-branch

#420 Fix bash completion of compose info
  etc/bash_completion.d/composer-cli
Labels: f28-branch, master, rhel7-extras, rhel8-branch

#438 Set TCP listen backlog for API socket to SOMAXCONN
  src/sbin/lorax-composer
Labels: f28-branch, master, rhel7-extras, rhel8-branch

#442 Only include specific blueprints in the rpm
  lorax.spec
Labels: rhel8-branch
