Repository weldr/lorax, pull requests merged in 2019-03, with the labels that each got.

#626 Fix handling of deleted blueprints
  src/pylorax/api/recipes.py
  src/pylorax/api/v0.py
  tests/pylorax/test_server.py
Labels: master

#623 New test: Build qcow2 compose and test it with QEMU-KVM
  Makefile
  tests/cli/test_compose_qcow2.sh
Labels: rhel8-branch

#625 New test: Build live-iso and boot with KVM
  Makefile
  tests/cli/test_compose_live-iso.sh
  tests/test_cli.sh
Labels: master

#630 New test: Build live-iso and boot with KVM
  Makefile
  tests/cli/test_compose_live-iso.sh
  tests/test_cli.sh
Labels: rhel8-branch

#631 New test: Build live-iso and boot with KVM
  Makefile
  tests/cli/test_compose_live-iso.sh
  tests/test_cli.sh
Labels: rhel7-extras

#635 Allow testing installed RPMs instead of source
  tests/cli/test_blueprints_sanity.sh
  tests/cli/test_build_and_deploy_aws.sh
  tests/cli/test_build_and_deploy_azure.sh
  tests/cli/test_build_and_deploy_openstack.sh
  tests/cli/test_build_and_deploy_vmware.sh
  tests/cli/test_compose_ext4-filesystem.sh
  tests/cli/test_compose_live-iso.sh
  tests/cli/test_compose_partitioned-disk.sh
  tests/cli/test_compose_qcow2.sh
  tests/cli/test_compose_sanity.sh
  tests/cli/test_compose_tar.sh
  tests/test_cli.sh
Labels: master, rhel7-extras, rhel8-branch

#633 Use make ci inside test-in-copy target
  Makefile
Labels: master, rhel8-branch

#632 Add blacklist_exceptions to multipath.conf
  share/templates.d/99-generic/runtime-postinstall.tmpl
Labels: f30-branch, master

#641 Do not include /usr/bin/delv
  share/runtime-cleanup.tmpl
Labels: rhel7-branch

#647 Don't remove chmem and lsmem from install.img
  share/runtime-cleanup.tmpl
Labels: rhel7-branch

#629 Backport cancel_func fixes
  src/pylorax/installer.py
Labels: rhel8-branch

#652 Don't remove chmem and lsmem from install.img
  share/templates.d/99-generic/runtime-cleanup.tmpl
Labels: master

#653 pylorax.ltmpl: Add a test for missing quotes
  tests/pylorax/templates/parse-missing-quote.tmpl
  tests/pylorax/test_ltmpl.py
Labels: master

#657 Switch the --virt-uefi method to use SecureBoot
  docs/livemedia-creator.rst
  src/pylorax/installer.py
  src/sbin/livemedia-creator
Labels: f30-branch, master

#659 qemu wasn't restoring the terminal if it was terminated early
  src/pylorax/installer.py
Labels: f30-branch, master

#663 Make it easier to generate docs for the next release
  Dockerfile.test
  Makefile
  docs/conf.py
Labels: master
