Repository weldr/lorax, pull requests merged in 2019-11, with the labels that each got.

#898 docs: Increase root filesystem to 2000 in rhel-minimal.ks
  docs/rhel-container.ks
  docs/rhel-livemedia.ks
  docs/rhel-minimal.ks
  docs/rhel-minimized.ks
  docs/rhel-openstack.ks
  docs/rhel-vagrant.ks
Labels: rhel8-branch

#911 fix typo in api docstring
  src/pylorax/api/v1.py
Labels: ACK

#915 tests: If TEST_OS isn't specified then match the host OS
  Makefile
Labels: rhel8-branch

#914 tests: enable compose_ext4 test to use CDN repos
  tests/cli/test_compose_ext4-filesystem.sh
Labels: rhel7-extras
