Repository weldr/lorax, pull requests merged in 2019-02, with the labels that each got.

#591 Make sure compose build tests run with SELinux in enforcing mode
  tests/cli/test_build_and_deploy_aws.sh
  tests/cli/test_build_and_deploy_azure.sh
  tests/cli/test_build_and_deploy_openstack.sh
  tests/cli/test_build_and_deploy_vmware.sh
  tests/cli/test_compose_ext4-filesystem.sh
  tests/cli/test_compose_partitioned-disk.sh
Labels: rhel7-extras

#592 Make sure compose build tests run with SELinux in enforcing mode
  tests/cli/test_build_and_deploy_aws.sh
  tests/cli/test_build_and_deploy_azure.sh
  tests/cli/test_build_and_deploy_openstack.sh
  tests/cli/test_build_and_deploy_vmware.sh
  tests/cli/test_compose_ext4-filesystem.sh
  tests/cli/test_compose_partitioned-disk.sh
Labels: master

#593 Azure: Use existing storage account and record date/time of VM creation
  tests/cli/test_build_and_deploy_azure.sh
Labels: rhel8-branch

#601 Move manpages into the correct subpackages
  lorax.spec
Labels: master

#606 Remove 3G minimum from lorax-composer
  lorax.spec
  src/pylorax/api/compose.py
Labels: master, rhel8-branch

#604 New test: Verify tar images with Docker and systemd-nspawn
  Makefile
  tests/cli/test_compose_ext4-filesystem.sh
  tests/cli/test_compose_partitioned-disk.sh
  tests/cli/test_compose_tar.sh
Labels: master

#611 New test: Verify tar images with Docker and systemd-nspawn
  Makefile
  tests/cli/test_compose_ext4-filesystem.sh
  tests/cli/test_compose_partitioned-disk.sh
  tests/cli/test_compose_tar.sh
Labels: rhel8-branch

#599 Drop auth from the kickstart examples
  docs/rhel-container.ks
  docs/rhel-livemedia.ks
  docs/rhel-minimal.ks
  docs/rhel-minimized.ks
  docs/rhel-openstack.ks
  docs/rhel-vagrant.ks
Labels: master, rhel8-branch

#605 Removed remnants of fedora branding.
  docs/rhel-atomic-pxe-live-novirt.ks
  docs/rhel-livemedia.ks
Labels: rhel8-branch

#618 New test: test qcow2 image with KVM
  Makefile
  tests/cli/test_compose_qcow2.sh
Labels: master

#624 Remove lorax-composer tests
  Makefile
  tests/cli/test_blueprints_sanity.sh
  tests/cli/test_compose_sanity.sh
  tests/composer/test_blueprints.py
  tests/composer/test_http_client.py
  tests/composer/test_utilities.py
  tests/pylorax/blueprints/atlas.toml
  tests/pylorax/blueprints/custom-base.toml
  tests/pylorax/blueprints/development.toml
  tests/pylorax/blueprints/glusterfs.toml
  tests/pylorax/blueprints/http-server.toml
  tests/pylorax/blueprints/jboss.toml
  tests/pylorax/blueprints/kubernetes.toml
  tests/pylorax/repos/multiple.repo
  tests/pylorax/repos/other.repo
  tests/pylorax/repos/single.repo
  tests/pylorax/results/custom-base.dict
  tests/pylorax/results/custom-base.toml
  tests/pylorax/results/full-recipe.dict
  tests/pylorax/results/full-recipe.toml
  tests/pylorax/results/minimal.dict
  tests/pylorax/results/minimal.toml
  tests/pylorax/results/modules-only.dict
  tests/pylorax/results/modules-only.toml
  tests/pylorax/results/packages-only.dict
  tests/pylorax/results/packages-only.toml
  tests/pylorax/source/bad-repo.toml
  tests/pylorax/source/replace-repo.toml
  tests/pylorax/source/test-repo.json
  tests/pylorax/source/test-repo.toml
  tests/pylorax/test_compose.py
  tests/pylorax/test_crossdomain.py
  tests/pylorax/test_projects.py
  tests/pylorax/test_recipes.py
  tests/pylorax/test_server.py
  tests/pylorax/test_workspace.py
  tests/pylorax/test_yumbase.py
  tests/test_cli.sh
Labels: rhel7-branch
