Repository weldr/lorax, pull requests merged in 2019-06, with the labels that each got.

#751 test: Don't wait on --sit when test succeeds
  test/composertest.py
Labels: no-test

#753 tests: Update openssh-server to v8.*
  tests/pylorax/blueprints/example-append.toml
  tests/pylorax/blueprints/example-http-server.toml
  tests/pylorax/test_server.py
Labels: rhel8-branch

#744 Remove PR template in favor of branch protection rules
  .github/pull_request_template.md
Labels: master

#738 Fix for Azure test
  tests/cli/test_build_and_deploy_azure.sh
Labels: rhel7-extras

#758 Updates for setup/teardown in test_cli.sh
  tests/test_cli.sh
Labels: rhel7-extras

#766 Enable networking in lorax-composer templates
  share/composer/ami.ks
  share/composer/ext4-filesystem.ks
  share/composer/live-iso.ks
  share/composer/openstack.ks
  share/composer/partitioned-disk.ks
  share/composer/qcow2.ks
  share/composer/tar.ks
  share/composer/vhd.ks
  share/composer/vmdk.ks
Labels: rhel7-extras

#733 Revert "test: Disable test_live_iso test"
  test/check-cli
Labels: master

#765 Backport changes for Cockpit CI to RHEL 7
  Makefile
  test/README.md
  test/check-api
  test/check-cli
  test/check-cloud
  test/composertest.py
  test/run
  test/vm.install
  tests/cli/lib/lib.sh
  tests/cli/test_blueprints_sanity.sh
  tests/cli/test_build_and_deploy_aws.sh
  tests/cli/test_build_and_deploy_azure.sh
  tests/cli/test_build_and_deploy_openstack.sh
  tests/cli/test_build_and_deploy_vmware.sh
  tests/cli/test_compose_ext4-filesystem.sh
  tests/cli/test_compose_live-iso.sh
  tests/cli/test_compose_partitioned-disk.sh
  tests/cli/test_compose_qcow2.sh
  tests/cli/test_compose_sanity.sh
  tests/cli/test_compose_tar.sh
  tests/test_cli.sh
  tests/testenv.sh
Labels: rhel7-extras

#768 Do not generate journal.xml from beakerlib
  tests/test_cli.sh
Labels: master

#767 Remove unused shell script
  tests/lib/testlib.sh
Labels: master
