Repository weldr/lorax, pull requests merged in 2019-10, with the labels that each got.

#862 tests: unskip Azure scenario
  test/check-cloud
Labels: master

#880 tests: Document Azure setup
  test/README.md
  tests/cli/test_build_and_deploy_azure.sh
Labels: ACK, master, no-test, rhel7-extras, rhel8-branch

#879 tests: unskip Azure scenario
  test/check-cloud
Labels: rhel7-extras

#877 tests: unskip Azure scenario
  test/check-cloud
Labels: rhel8-branch

#891 Disable some compose types on other architectures
  src/pylorax/api/compose.py
  src/pylorax/api/v0.py
  tests/pylorax/test_compose.py
  tests/pylorax/test_server.py
Labels: rhel8-branch

#890 Disable some compose types on other architectures
  src/pylorax/api/compose.py
  src/pylorax/api/v0.py
  tests/pylorax/test_compose.py
  tests/pylorax/test_server.py
Labels: master

#889 Add live iso support to s390
  share/templates.d/99-generic/live/config_files/s390/cdboot.prm
  share/templates.d/99-generic/live/s390.tmpl
Labels: rhel8-branch
