Repository weldr/lorax, pull requests merged in 2019-04, with the labels that each got.

#670 Add documentation references to lorax-composer service files
  systemd/lorax-composer.service
  systemd/lorax-composer.socket
Labels: master

#671 Add a new compose type for Hyper-V
  docs/composer-cli.rst
  share/composer/hyper-v.ks
  src/pylorax/api/compose.py
  tests/cli/test_compose_sanity.sh
  tests/pylorax/test_server.py
Labels: master, rhel8-branch

#667 Add -iso-level 3 when the install.img is > 4GiB
  share/templates.d/99-generic/aarch64.tmpl
  share/templates.d/99-generic/arm.tmpl
  share/templates.d/99-generic/live/aarch64.tmpl
  share/templates.d/99-generic/live/ppc64le.tmpl
  share/templates.d/99-generic/live/x86.tmpl
  share/templates.d/99-generic/ppc64le.tmpl
  share/templates.d/99-generic/s390.tmpl
  share/templates.d/99-generic/x86.tmpl
Labels: f30-branch, master

#683 Fixes for locked root account test
  tests/cli/lib/root_account.sh
  tests/cli/test_compose_qcow2.sh
Labels: rhel8-branch

#688 Add test for starting compose with deleted blueprint
  tests/cli/test_blueprints_sanity.sh
Labels: rhel8-branch

#695 Update VMware info for VMware testing
  tests/cli/test_build_and_deploy_vmware.sh
Labels: master

#694 Update VMware info for VMware testing
  tests/cli/test_build_and_deploy_vmware.sh
Labels: rhel8-branch

#693 Update VMware info for VMware testing
  tests/cli/test_build_and_deploy_vmware.sh
Labels: rhel7-extras

#594 Azure: Use existing storage account and record date/time of VM creation
  tests/cli/test_build_and_deploy_azure.sh
Labels: rhel7-extras

#690 Add test for starting compose with deleted blueprint
  tests/cli/test_blueprints_sanity.sh
Labels: master

#700 Backport deleted recipes handling to rhel7-extras
  src/pylorax/api/recipes.py
  src/pylorax/api/v0.py
  tests/pylorax/test_server.py
Labels: rhel7-extras

#691 Add test for starting compose with deleted blueprint
  tests/cli/test_blueprints_sanity.sh
Labels: rhel7-extras
