Repository weldr/lorax, pull requests merged in 2020-08, with the labels that each got.

#1055 Switch VMware testing env to improve stability results
  tests/cli/test_build_and_deploy_vmware.sh
Labels: rhel7-extras

#1056 Skip test_z_diff() if running against osbuild-composer
  tests/composer/test_blueprints.py
Labels: rhel8-branch

#1058 Switch VMware testing env to improve stability results
  tests/cli/test_build_and_deploy_vmware.sh
Labels: master

#1061 rhel-livemedia.ks: Add anaconda-live package to the example kickstart
  docs/rhel-livemedia.ks
Labels: rhel8-branch

#1060 tests: Push example blueprints b/c they may not exist
  tests/composer/test_blueprints.py
Labels: rhel8-branch

#1062 tests: Fix diff test BACKEND check
  tests/composer/test_blueprints.py
Labels: rhel8-branch
