Repository weldr/lorax, pull requests merged in 2020-04, with the labels that each got.

#984 Update datastore for VMware testing
  tests/cli/test_build_and_deploy_vmware.sh
Labels: master

#982 tests: pip install future
  tests/cli/test_build_and_deploy_openstack.sh
Labels: rhel7-extras

#985 Update datastore for VMware testing
  tests/cli/test_build_and_deploy_vmware.sh
Labels: rhel7-extras

#939 [7.9] Add test for canceling a running compose
  tests/cli/test_compose_sanity.sh
Labels: rhel7-extras

#967 Update TestApi skip message because of a bug
  test/check-api
Labels: rhel7-extras

#993 Add --no-system-repos to lorax-composer
  src/sbin/lorax-composer
Labels: rhel7-extras

#996 lorax: Add --skip-branding cmdline argument
  docs/lorax.rst
  src/pylorax/__init__.py
  src/pylorax/cmdline.py
  src/pylorax/treebuilder.py
  src/sbin/lorax
  tests/pylorax/test_treebuilder.py
Labels: f32-branch, master

#994 [tests] don't add only rel-eng optional repo for live-iso
  tests/cli/test_compose_live-iso.sh
Labels: rhel7-extras

#930 [7.9] Add test for running composer with --no-system-repos option
  test/check-cli
  test/run
  tests/cli/test_repos_sanity.sh
Labels: rhel7-extras

#999 rsyslog: Disable journal ratelimits during install
  share/templates.d/99-generic/config_files/common/rsyslog.conf
Labels: master

#1002 lmc-no-virt: Add requirement on anaconda-install-env-deps
  lorax.spec
Labels: master
