Repository weldr/lorax, pull requests merged in 2020-01, with the labels that each got.

#929 Add test for running composer with --no-system-repos option
  test/check-cli
  test/run
  tests/cli/test_repos_sanity.sh
Labels: rhel8-branch

#934 composer-cli: Increase DELETE timeout to 120s
  src/composer/http_client.py
Labels: rhel8-branch

#933 Add test for canceling a running compose
  tests/cli/test_compose_sanity.sh
Labels: master

#937 AWS test: take into account different instance type for non x86
  tests/cli/playbooks/aws/instance.yml
  tests/cli/test_build_and_deploy_aws.sh
  tests/cli/test_compose_sanity.sh
Labels: master

#938 Add test for canceling a running compose
  tests/cli/test_compose_sanity.sh
Labels: rhel8-branch

#940 lorax-composer: Enable ami on aarch64
  src/pylorax/api/compose.py
  tests/cli/test_compose_sanity.sh
Labels: master

#944 tests: Enable Elastic Network Adapter support for AWS
  tests/cli/test_build_and_deploy_aws.sh
Labels: master

#947 tests: check for failed compose before trying to cancel
  tests/cli/test_compose_sanity.sh
Labels: master

#949 tests: Check for cloud-init presence in azure image
  tests/cli/test_build_and_deploy_azure.sh
Labels: rhel8-branch

#951 Add tests for metapackages and package name globs
  tests/pylorax/test_projects.py
Labels: master

#953 Add tests for metapackages and package name globs
  tests/pylorax/test_projects.py
Labels: rhel8-branch

#950 tests: remove --test=2 from compose_sanity
  tests/cli/test_compose_sanity.sh
Labels: master

#952 lorax: Log dnf solver debug data in ./debugdata/
  src/pylorax/dnfbase.py
Labels: ACK

#954 tests: remove --test=2 from compose_sanity
  tests/cli/test_compose_sanity.sh
Labels: rhel8-branch

#956 tests: run ssh commands in batch mode
  tests/cli/lib/lib.sh
  tests/cli/test_build_and_deploy_azure.sh
Labels: master

#958 tests: run ssh commands in batch mode
  tests/cli/lib/lib.sh
  tests/cli/test_build_and_deploy_azure.sh
Labels: rhel8-branch

#703 Automation for Alibaba cloud
  test/check-cloud
  tests/cleanup/remove_old_objects_alibaba.sh
  tests/cli/test_compose_alibaba.sh
Labels: master

#962 tests: remove ALI_DIR after we're done using the cli
  tests/cli/test_compose_alibaba.sh
Labels: master
