Repository weldr/lorax, pull requests merged in 2020-05, with the labels that each got.

#1008 Don't use f-string without interpolation
  src/lifted/upload.py
Labels: master

#1000 rsyslog: Disable journal ratelimits during install
  share/templates.d/99-generic/config_files/common/rsyslog.conf
Labels: rhel8-branch

#1015 mksquashfs: Catch errors with mksquashfs and report them
  src/pylorax/__init__.py
  src/pylorax/creator.py
  src/pylorax/treebuilder.py
Labels: master

#909 [7.9]: Unskip AWS test scenario
  test/check-cloud
Labels: rhel7-extras
