Repository weldr/lorax, pull requests merged in 2020-02, with the labels that each got.

#959 Test & cleanup script for Alibaba cloud
  test/check-cloud
  tests/cleanup/remove_old_objects_alibaba.sh
  tests/cli/test_compose_alibaba.sh
Labels: rhel8-branch

#955 lorax: Catch rootfs out of space failures
  src/pylorax/treebuilder.py
  tests/pylorax/test_imgutils.py
Labels: master

#960 Add new test to run 'test' and 'check' in cockpit ci
  test/check-cli
  test/run
  tests/cli/test_ci.sh
Labels: no-test, rhel8-branch

#969 lorax: Add eject back into the boot.iso
  share/templates.d/99-generic/runtime-cleanup.tmpl
  share/templates.d/99-generic/runtime-install.tmpl
Labels: master, rhel8-branch
